/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Article = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'published' : IDL.Bool,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToWatchlist' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearWatchlist' : IDL.Func([], [], []),
  'createArticle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'fetchFinancialNews' : IDL.Func([IDL.Text], [IDL.Text], []),
  'fetchMarketSummary' : IDL.Func([], [IDL.Text], []),
  'fetchStockQuote' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOwnArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishArticle' : IDL.Func([IDL.Int], [], []),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Article = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'published' : IDL.Bool,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToWatchlist' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearWatchlist' : IDL.Func([], [], []),
    'createArticle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'fetchFinancialNews' : IDL.Func([IDL.Text], [IDL.Text], []),
    'fetchMarketSummary' : IDL.Func([], [IDL.Text], []),
    'fetchStockQuote' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOwnArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishArticle' : IDL.Func([IDL.Int], [], []),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };